-- ============================================================
-- Location Mapping : Archipelago location_id → code tracker
-- ============================================================
-- IDs sources : https://github.com/Xtruh/LiesOfAP/blob/main/LiesOfAP/src/IDs.cpp
--
-- Format : [archipelago_location_id] = { "@/Map/Zone/Section" }
--   Le préfixe "@" indique une section de map (AvailableChestCount)
--   Sans "@" : item hébergé { "item_code", "item_type" }
--
-- Locations : 1102 au total, réparties sur Ch01-Ch11b + DLC Ch01-Ch05
-- À remplir au fur et à mesure que les sections de map sont créées.
-- ============================================================

LOCATION_MAPPING = {

    -- =========================================================
    -- Ch01 - Krat Central Station (IDs 1-9)
    -- =========================================================
    [  1] = { "@KCS - Locations/Bench outside train" },
    [  2] = { "@KCS - Locations/Bench inside lobby" },
    [  3] = { "@KCS - Locations/Bathroom" },
    [  4] = { "@KCS - Locations/Small room near bar" },
    [  5] = { "@KCS - Locations/Small room with train info board" },
    [  6] = { "@KCS - Locations/Shortcut to station lobby" },
    [  7] = { "@KCS - Locations/Krat Central Station Main Entrance Key" },
    [  8] = { "@KCS - Locations/Workshop Union Lightweight Frame" },
    [  9] = { "@KCS - Locations/Behind Police Puppet" },


    -- =========================================================
    -- Ch01 - Krat Central Station Plaza (IDs 10-24, 343-344)
    -- =========================================================
    [ 10] = { "@KCS Plaza - Locations/Wagon with Puppet Dog on top" },
    [ 11] = { "@KCS Plaza - Locations/Broken wagon" },
    [ 12] = { "@KCS Plaza - Locations/Boxes near broken wagon" },
    [ 13] = { "@KCS Plaza - Locations/Bench near staircase" },
    [ 14] = { "@KCS Plaza - Locations/Locked shortcut gate upstairs" },
    [ 15] = { "@KCS Plaza - Locations/Beside Puppet banging door" },
    [ 16] = { "@KCS Plaza - Locations/Upstairs by rubble cliffside" },
    [ 17] = { "@KCS Plaza - Locations/Destructible barrel in alley" },
    [ 18] = { "@KCS Plaza - Locations/Upstairs before dropdown in alley" },
    [ 19] = { "@KCS Plaza - Locations/Gate at dead-end in alley" },
    [ 20] = { "@KCS Plaza - Locations/Downstairs with Puppet Dog" },
    [ 21] = { "@KCS Plaza - Locations/Training dummy by merchant" },
    [ 22] = { "@KCS Plaza - Locations/Path before Parade Master" },
    [ 23] = { "@KCS Plaza - Locations/Parade Leader's Ergo" },
    [ 24] = { "@KCS Plaza - Locations/Quartz" },
    [343] = { "@KCS Plaza - Locations/The Atoned's Hunting Apparel" },
    [344] = { "@KCS Plaza - Locations/Legion Caliber" },

    -- =========================================================
    -- Hotel Krat
    -- =========================================================
    [ 25] = { "@Hotel Krat Entrance - Locations/wagon near fountain after Parade Master" },
    [ 26] = { "@Hotel Krat Entrance - Locations/wagon near dead-end after Parade Master" },
    [ 27] = { "@Hotel Krat Entrance - Locations/garden before Hotel Krat door" },
    [ 28] = { "@Hotel Krat Entrance - Locations/pile of corpses before Hotel Krat door" },
    [ 29] = { "@Hotel Krat Main Floor - Locations/table near Antonia" },
    [ 79] = { "@Hotel Krat Upper Floor - Locations/from Gepetto after Scrapped Watchman" },
    [ 283] = { "@Hotel Krat Main Floor - Locations/given by Antonia" },

    -- =========================================================
    -- Elysion Boulevard (IDs 30-61, 194-195)
    -- =========================================================
    [ 30] = { "@Elysion Boulevard - Locations/bench on lower platform" },
    [ 31] = { "@Elysion Boulevard - Locations/wagon with ambush from above" },
    [ 32] = { "@Elysion Boulevard - Locations/chest before ladder" },
    [ 33] = { "@Elysion Boulevard - Locations/rooftops ladder shortcut" },
    [ 34] = { "@Elysion Boulevard - Locations/rooftops near a red sign" },
    [ 35] = { "@Elysion Boulevard - Locations/corner of room to Brtsto De Krat's roof" },
    [ 36] = { "@Elysion Boulevard - Locations/wooden beam outside Bristo De Krat's rooftop" },
    [ 37] = { "@Elysion Boulevard - Locations/dead-end of Bistro De Krat's roof" },
    [ 38] = { "@Elysion Boulevard - Locations/Bristo De Krat ladder, down" },
    [ 39] = { "@Elysion Boulevard - Locations/shortcut back to the start" },
    [ 40] = { "@Elysion Boulevard - Locations/Bristo De Krat ladder, up to dead-end" },
    [ 41] = { "@Elysion Boulevard - Locations/Bristo De Krat's roof, barrels in a corner" },
    [ 42] = { "@Elysion Boulevard - Locations/Bristo De Krat's roof, small ladder down" },
    [ 43] = { "@Elysion Boulevard - Locations/Bristo De Krat's roof, top near ladder" },
    [ 44] = { "@Elysion Boulevard - Locations/Bristo De Krat's roof, top near a drop down" },
    [ 45] = { "@Elysion Boulevard - Locations/couch" },
    [ 46] = { "@Elysion Boulevard - Locations/in a chest on the roof" },
    [ 47] = { "@Elysion Boulevard - Locations/wooden beam before Red Butterfly" },
    [ 48] = { "@Elysion Boulevard - Locations/top of the roof before Red Butterfly" },
    [ 49] = { "@Elysion Boulevard - Locations/Red Butterfly drop" },
    [ 50] = { "@Elysion Boulevard - Locations/lamp surrounded by dog Puppets" },
    [ 51] = { "@Elysion Boulevard - Locations/wagon near a shortcut" },
    [ 52] = { "@Elysion Boulevard - Locations/small alley in the streets" },
    [ 53] = { "@Elysion Boulevard - Locations/electric trap in alley in the streets" },
    [ 54] = { "@Elysion Boulevard - Locations/wagon in the streets" },
    [ 55] = { "@Elysion Boulevard - Locations/alley with Toma and electric traps" },
    [ 56] = { "@Elysion Boulevard - Locations/chest blocked by electric trap" },
    [ 57] = { "@Elysion Boulevard - Locations/across bridge near Red Butterfly" },
    [ 58] = { "@Elysion Boulevard - Locations/dropped from baton wielding Police Puppet" },
    [ 59] = { "@Elysion Boulevard - Locations/red boxes after Police Puppet" },
    [ 60] = { "@Elysion Boulevard - Locations/Infront of shortcut to Toma" },
    [ 61] = { "@Elysion Boulevard - Locations/electric trap before Mad Donkey" },
    [194] = { "@Elysion Boulevard - Locations/quartz" },
    [195] = { "@Elysion Boulevard - Locations/Owl Doctor's Hunting Apparel" },

    -- =========================================================
    -- Elysion Boulevard Alchemist Bridge (IDs 62-66)
    -- =========================================================
    [ 62] = { "@Elysion Boulevard Alchemist Bridge - Locations/Mad Donkey's Hunting Apparal" },
    [ 63] = { "@Elysion Boulevard Alchemist Bridge - Locations/Mad Donkey's Mask" },
    [ 64] = { "@Elysion Boulevard Alchemist Bridge - Locations/Krat City Hall Key" },
    [ 65] = { "@Elysion Boulevard Alchemist Bridge - Locations/Enigma Assembly Tool" },
    [ 66] = { "@Elysion Boulevard Alchemist Bridge - Locations/wagon at end of the bridge" },

    -- =========================================================
    -- Krat City Hall (IDs 67-78)
    -- =========================================================
    [ 67] = { "@Krat City Hall - Locations/lamp near electric trap" },
    [ 68] = { "@Krat City Hall - Locations/corpse by a wagon" },
    [ 69] = { "@Krat City Hall - Locations/before opening shortcut" },
    [ 70] = { "@Krat City Hall - Locations/after opening shortcut" },
    [ 71] = { "@Krat City Hall - Locations/left before Scrapped Watchman" },
    [ 72] = { "@Krat City Hall - Locations/chest before Scrapped Watchman" },
    [ 73] = { "@Krat City Hall - Locations/Overcharged Storage Battery" },
    [ 74] = { "@Krat City Hall - Locations/Broken Hero's Ergo" },
    [ 75] = { "@Krat City Hall - Locations/Core" },
    [ 76] = { "@Krat City Hall - Locations/Quartz" },
    [ 77] = { "@Krat City Hall - Locations/Small Wooden Officer Puppet" },
    [ 78] = { "@Krat City Hall - Locations/after Scrapped Watchman" },

    -- =========================================================
    -- Workshop Union Entrance (IDs 80-88)
    -- =========================================================
    [ 80] = { "@Workshop Union Entrance - Locations/wagon after opening door" },
    [ 81] = { "@Workshop Union Entrance - Locations/left side before roofs" },
    [ 82] = { "@Workshop Union Entrance - Locations/red rooftop" },
    [ 83] = { "@Workshop Union Entrance - Locations/ladder from red rooftops, down" },
    [ 84] = { "@Workshop Union Entrance - Locations/dead-end down ladder from red rooftops" },
    [ 85] = { "@Workshop Union Entrance - Locations/destructible boxes at a side path" },
    [ 86] = { "@Workshop Union Entrance - Locations/destructible boxes before bridge" },
    [ 87] = { "@Workshop Union Entrance - Locations/destructible boxes by the phone riddle" },
    [ 88] = { "@Workshop Union Entrance - Locations/staircase after bridge" },

    -- =========================================================
    -- Venigni's Workshop (IDs 89-147)
    -- =========================================================
    [ 89] = { "@Venigni's Workshop - Locations/near Workshop Union Entrance stargazer" },
    [ 90] = { "@Venigni's Workshop - Locations/upstairs from Workshop Union Entrance stargazer" },
    [ 91] = { "@Venigni's Workshop - Locations/safe after a dropdown" },
    [ 92] = { "@Venigni's Workshop - Locations/behind where the floor can fall" },
    [ 93] = { "@Venigni's Workshop - Locations/chest inside the warehouse" },
    [ 94] = { "@Venigni's Workshop - Locations/left side warehouse" },
    [ 95] = { "@Venigni's Workshop - Locations/warehouse upper area" },
    [ 96] = { "@Venigni's Workshop - Locations/corner before Shield Puppet" },
    [ 97] = { "@Workshop Union Culvert - Locations/Legion Caliber" },
    [ 98] = { "@Workshop Union Culvert - Locations/Hidden Moonstone - Duel Shield" },
    [ 99] = { "@Workshop Union Culvert - Locations/Red Butterfly drop" },
    [100] = { "@Workshop Union Culvert - Locations/after Red Butterfly" },
    [101] = { "@Workshop Union Culvert - Locations/pipe by the Workshop Union Culvert stargazer" },
    [102] = { "@Workshop Union Culvert - Locations/corruption swamp, right side" },
    [103] = { "@Workshop Union Culvert - Locations/corruption swamp, across from pipe" },
    [104] = { "@Workshop Union Culvert - Locations/corruption swamp, ambush" },
    [105] = { "@Workshop Union Culvert - Locations/corruption swamp, Red Butterfly drop" },
    [106] = { "@Workshop Union Culvert - Locations/corruption swamp dead-end, right" },
    [107] = { "@Workshop Union Culvert - Locations/corruption swamp dead-end, left" },
    [108] = { "@Workshop Union Culvert - Locations/rolling fireball entrance" },
    [109] = { "@Workshop Union Culvert - Locations/rolling fireball dead-end" },
    [110] = { "@Workshop Union Culvert - Locations/rolling fireball shortcut" },
    [111] = { "@Workshop Union Culvert - Locations/dead-end near Survivor exit" },
    [112] = { "@Workshop Union Culvert - Locations/ladder shortcut to Puppet of the Future" },
    [113] = { "@Workshop Union Culvert - Locations/rolling fireball chest" },
    [114] = { "@Workshop Union Culvert - Locations/near puppet that smashes a wall" },
    [115] = { "@Workshop Union Culvert - Locations/beside Black Cat and Red Fox" },
    [116] = { "@Workshop Union Culvert - Locations/oposite red pipe before Shovel enemy" },
    [117] = { "@Workshop Union Culvert - Locations/ladder shortcut by first Trinity Key door" },
    [118] = { "@Workshop Union Culvert - Locations/Blue Blood's Tailcoat" },
    [119] = { "@Workshop Union Culvert - Locations/Quartz - Trinity Key" },
    [120] = { "@Workshop Union Culvert - Locations/red pipe drop down" },
    [121] = { "@Workshop Union Culvert - Locations/Swordsmanship Master's Amulet" },
    [122] = { "@Workshop Union Culvert - Locations/Hidden Moonstone - Shovel elite" },
    [123] = { "@Workshop Union Culvert - Locations/beside lever to drain the decay" },
    [124] = { "@Venigni's Workshop - Locations/room upstairs next to the hanging puppets" },
    [125] = { "@Venigni's Workshop - Locations/beneath the hanging puppets" },
    [126] = { "@Venigni's Workshop - Locations/upstairs next to the hanging puppets" },
    [127] = { "@Workshop Union Culvert - Locations/Survivor's Hunting Apparel" },
    [128] = { "@Workshop Union Culvert - Locations/Survivor's Mask" },
    [129] = { "@Venigni's Workshop - Locations/other side of pipe shortcut" },
    [130] = { "@Workshop Union Culvert - Locations/Quartz - Puppets of the Future" },
    [131] = { "@Workshop Union Culvert - Locations/Radiant Ergo Chunk" },
    [132] = { "@Workshop Union Culvert - Locations/Puppet of the Future arena pickup 1" },
    [133] = { "@Workshop Union Culvert - Locations/Puppet of the Future arena pickup 2" },
    [134] = { "@Workshop Union Culvert - Locations/Puppet of the Future arena pickup 3" },
    [135] = { "@Workshop Union Culvert - Locations/Puppet of the Future arena chest" },
    [136] = { "@Venigni Works Control Room - Locations/lower right platform near Shovel elite" },
    [137] = { "@Venigni Works Control Room - Locations/upstairs towards Venigni" },
    [138] = { "@Venigni Works Control Room - Locations/on metal beams towards Fuoco" },
    [139] = { "@Venigni Works Control Room - Locations/upper left platform near Venigni" },
    [140] = { "@Venigni Works Control Room - Locations/upper right platform near Venigni" },
    [141] = { "@Venigni Works Control Room - Locations/jump on the metal beams" },
    [142] = { "@Venigni Works Control Room - Locations/lower right platform near Venigni" },
    [143] = { "@Venigni Works Control Room - Locations/Workshop Union Standard Radiation Converter" },
    [144] = { "@Venigni Works Control Room - Locations/Hidden Moonstone" },
    [145] = { "@Venigni Works Control Room - Locations/High-powered Flame Amplifier" },
    [146] = { "@Venigni Works Control Room - Locations/King's Flame Ergo" },
    [147] = { "@Venigni Works Control Room - Locations/Flame Grindstone" },
    
    -- =========================================================
    -- MoonLight Town (IDs 148-168)
    -- =========================================================

    [148] = { "@MoonLight Town - Locations/tunnel leaving Venigni Works" },
    [149] = { "@MoonLight Town - Locations/behind boxes before the mines" },
    [150] = { "@MoonLight Town - Locations/minecart" },
    [151] = { "@MoonLight Town - Locations/scaffolding after the mines" },
    [152] = { "@MoonLight Town - Locations/behind box on scaffolding" },
    [153] = { "@MoonLight Town - Locations/chest on top of scaffolding" },
    [154] = { "@MoonLight Town - Locations/pit near explosive barrels" },
    [155] = { "@MoonLight Town - Locations/before wood wall that a Puppet breaks" },
    [156] = { "@MoonLight Town - Locations/Inside wood wall the Puppet breaks down" },
    [157] = { "@MoonLight Town - Locations/Shovel elite enemy drop" },
    [158] = { "@MoonLight Town - Locations/dropdown near fallen tree" },
    [159] = { "@MoonLight Town - Locations/well" },
    [160] = { "@MoonLight Town - Locations/shack near a campfire" },
    [161] = { "@MoonLight Town - Locations/collapsing bridge" },
    [162] = { "@MoonLight Town - Locations/first Red Butterfly drop" },
    [163] = { "@MoonLight Town - Locations/second Red Butterfly drop" },
    [164] = { "@MoonLight Town - Locations/gravestone after the Red Butterflies" },
    [165] = { "@MoonLight Town - Locations/chest, ambush with locked gate" },
    [166] = { "@MoonLight Town - Locations/on the ground, ambush with locked gate" },
    [167] = { "@MoonLight Town - Locations/lever to open the gate" },
    [168] = { "@MoonLight Town - Locations/gravestone before Atoned" },

    -- =========================================================
    -- Path of Misery (IDs 169-177, 1103)
    -- =========================================================

    [169] = { "@Path of Misery - Locations/shack after carcass cutscene" },
    [170] = { "@Path of Misery - Locations/shack towards collapsing bridge" },
    [171] = { "@Path of Misery - Locations/before collapsing bridge" },
    [172] = { "@Path of Misery - Locations/corner behind some destructable boxes" },
    [173] = { "@Path of Misery - Locations/statue you can pray to" },
    [174] = { "@Path of Misery - Locations/bench inside of the church" },
    [175] = { "@Path of Misery - Locations/chest behind Giango" },
    [176] = { "@Path of Misery - Locations/right side of bridge to St. Frangelico Cathedral Chapel" },
    [177] = { "@Path of Misery - Locations/end of bridge to St. Frangelico Cathedral Chapel" },
    [1103] = { "@Path of Misery - Locations/near stargazer after cable lift" },

    -- =========================================================
    -- St. Frangelico Cathedral Chapel (IDs 178-193, 278-279)
    -- =========================================================

    [178] = { "@St. Frangelico Cathedral Chapel - Locations/seat infront of organ" },
    [179] = { "@St. Frangelico Cathedral Chapel - Locations/opposite the ladder into the Cathedral" },
    [180] = { "@St. Frangelico Cathedral Chapel - Locations/decay pool at the bottom of the Cathedral" },
    [181] = { "@St. Frangelico Cathedral Chapel - Locations/drop down after some destructable objects" },
    [182] = { "@St. Frangelico Cathedral Chapel - Locations/second drop down after some destructable objects" },
    [183] = { "@St. Frangelico Cathedral Chapel - Locations/small wooden beam" },
    [184] = { "@St. Frangelico Cathedral Chapel - Locations/Dead-end after a Carcass enemy breaks down wall" },
    [185] = { "@St. Frangelico Cathedral Chapel - Locations/up on a wooden catwalk" },
    [186] = { "@St. Frangelico Cathedral Chapel - Locations/near lever to flip the direction of the elevator" },
    [187] = { "@St. Frangelico Cathedral Chapel - Locations/chest after water wheel drop off" },
    [188] = { "@St. Frangelico Cathedral Chapel - Locations/chest in a room that is exposed by draining decay pool" },
    [189] = { "@St. Frangelico Cathedral Chapel - Locations/chest after elevator up the cathedral drop off" },
    [190] = { "@St. Frangelico Cathedral Chapel - Locations/corpse near Shielded Carcass elite" },
    [191] = { "@St. Frangelico Cathedral Chapel - Locations/Shielded Carcass elite enemy drop" },
    [192] = { "@St. Frangelico Cathedral Chapel - Locations/up ladder near Shielded Carcass elite" },
    [193] = { "@St. Frangelico Cathedral Chapel - Locations/chest inside a cell" },
    [278] = { "@St. Frangelico Cathedral Chapel - Locations/Black Cat's Amulet" },
    [279] = { "@St. Frangelico Cathedral Chapel - Locations/Moster Sweeper's Hunting Apparel" },

    -- =========================================================
    -- St. Frangelico Cathedral Library (IDs 196-213)
    -- =========================================================

    [196] = { "@St. Frangelico Cathedral Library - Locations/next to St. Frangelico Cathedral Library stargazer" },
    [197] = { "@St. Frangelico Cathedral Library - Locations/Purple Butterfly drop" },
    [198] = { "@St. Frangelico Cathedral Library - Locations/behind a pillar near Purple Butterfly" },
    [199] = { "@St. Frangelico Cathedral Library - Locations/chest near Purple Butterfly" },
    [200] = { "@St. Frangelico Cathedral Library - Locations/before shortcut door near Purple Butterfly" },
    [201] = { "@St. Frangelico Cathedral Library - Locations/room with decay falling from above" },
    [202] = { "@St. Frangelico Cathedral Library - Locations/across the bridge" },
    [203] = { "@St. Frangelico Cathedral Library - Locations/altar near decay pool" },
    [204] = { "@St. Frangelico Cathedral Library - Locations/inside decay pool" },
    [205] = { "@St. Frangelico Cathedral Library - Locations/between a staircase and bookcase" },
    [206] = { "@St. Frangelico Cathedral Library - Locations/balcony" },
    [207] = { "@St. Frangelico Cathedral Library - Locations/altar near two angel statues" },
    [208] = { "@St. Frangelico Cathedral Library - Locations/safe near two angel statues" },
    [209] = { "@St. Frangelico Cathedral Library - Locations/dead-end with decay falling from ceiling" },
    [210] = { "@St. Frangelico Cathedral Library - Locations/altar near shortcut Archbishop" },
    [211] = { "@St. Frangelico Cathedral Library - Locations/above St. Frangelico Cathedral Library stargazer" },
    [212] = { "@St. Frangelico Cathedral Library - Locations/Fallen Archbishop Andreus drop" },
    [213] = { "@St. Frangelico Cathedral Library - Locations/after the elevator from Archbishop" },

    -- =========================================================
    -- Path of the Pilgrim (IDs 214-240, 495-498)
    -- =========================================================

    [214] = { "@Path of the Pilgrim - Locations/carcass dog and a bear trap" },
    [215] = { "@Path of the Pilgrim - Locations/upper ledge near Path of the Pilgrim stargazer" },
    [216] = { "@Path of the Pilgrim - Locations/barrel fire" },
    [217] = { "@Path of the Pilgrim - Locations/chest with carcass enemy ambush" },
    [218] = { "@Path of the Pilgrim - Locations/barrel fire with a Carcass dog ambush" },
    [219] = { "@Path of the Pilgrim - Locations/beneath the carcass bear before bear traps" },
    [220] = { "@Path of the Pilgrim - Locations/beneath the carcass bear after bear traps" },
    [221] = { "@Path of the Pilgrim - Locations/beneath the carcass bear on corpse" },
    [222] = { "@Path of the Pilgrim - Locations/Purple Butterfly drop" },
    [223] = { "@Path of the Pilgrim - Locations/pound left side" },
    [224] = { "@Path of the Pilgrim - Locations/pound right side" },
    [225] = { "@Path of the Pilgrim - Locations/right shack near entrance" },
    [226] = { "@Path of the Pilgrim - Locations/left side near entrance" },
    [227] = { "@Path of the Pilgrim - Locations/wood beam on roofs" },
    [228] = { "@Path of the Pilgrim - Locations/corpse near a counter" },
    [229] = { "@Path of the Pilgrim - Locations/elevator shortcut drop off" },
    [230] = { "@Path of the Pilgrim - Locations/top of elevator shortcut" },
    [231] = { "@Path of the Pilgrim - Locations/Carcass Elite drop" },
    [232] = { "@Path of the Pilgrim - Locations/corpse near Carcass Elite" },
    [233] = { "@Path of the Pilgrim - Locations/chest inside slum shack" },
    [234] = { "@Path of the Pilgrim - Locations/outside robber shack" },
    [235] = { "@Path of the Pilgrim - Locations/dropdown beneath the bridge" },
    [236] = { "@Path of the Pilgrim - Locations/beneath the bridge" },
    [237] = { "@Path of the Pilgrim - Locations/corpse near barrel fire" },
    [238] = { "@Path of the Pilgrim - Locations/by destructable boxes" },
    [239] = { "@Path of the Pilgrim - Locations/up ladder in parkour section" },
    [240] = { "@Path of the Pilgrim - Locations/ledge in parkour section" },
    [495] = { "@Path of the Pilgrim - Locations/given by Slum Resident" },
    [496] = { "@Path of the Pilgrim - Locations/after Slum Resident's trap" },
    [497] = { "@Path of the Pilgrim - Locations/Life Amulet +1" },
    [498] = { "@Path of the Pilgrim - Locations/Legion Caliber" },

    -- =========================================================
    -- Malum District (IDs 241-277, 280-282)
    -- =========================================================
    
    [241] = { "@Malum District - Locations/metal gate a carcass dog breaks" },
    [242] = { "@Malum District - Locations/up ladder on scaffolding" },
    [243] = { "@Malum District - Locations/behind destructable barrel on a stool" },
    [244] = { "@Malum District - Locations/behind where the floor can fall in the brewly" },
    [245] = { "@Malum District - Locations/chest after falling in the brewly" },
    [246] = { "@Malum District - Locations/corpse near a staircase at the brewly" },
    [247] = { "@Malum District - Locations/shortcut door in the brewly" },
    [248] = { "@Malum District - Locations/ladder that leads outside" },
    [249] = { "@Malum District - Locations/exit that leads outside" },
    [250] = { "@Malum District - Locations/Carcass Elite drop" },
    [251] = { "@Malum District - Locations/right side of the outside" },
    [252] = { "@Malum District - Locations/chest in the outside" },
    [253] = { "@Malum District - Locations/left side of the outside" },
    [254] = { "@Malum District - Locations/back right side of the outside" },
    [255] = { "@Malum District - Locations/Red Butterfly drop" },
    [256] = { "@Malum District - Locations/roofs where the floor can break" },
    [257] = { "@Malum District - Locations/right side of the roofs" },
    [258] = { "@Malum District - Locations/pillar on the roofs" },
    [259] = { "@Malum District - Locations/left side of the roofs" },
    [260] = { "@Malum District - Locations/chest on the roofs" },
    [261] = { "@Malum District - Locations/cell in the back left side of the outside" },
    [262] = { "@Malum District - Locations/jump near shortcut gate" },
    [263] = { "@Malum District - Locations/after jump near shortcut gate" },
    [264] = { "@Malum District - Locations/alley nearshortcut gate" },
    [265] = { "@Malum District - Locations/staircase by shortcute gate" },
    [266] = { "@Malum District - Locations/alley downstairs by barrel fire" },
    [267] = { "@Malum District - Locations/corner by cages with carcass dogs" },
    [268] = { "@Malum District - Locations/ledge before trap from Black Rabbit Brotherhood" },
    [269] = { "@Malum District - Locations/gate that a carcass dog breaks" },
    [270] = { "@Malum District - Locations/ladder near gate" },
    [271] = { "@Malum District - Locations/piano inside the bar" },
    [272] = { "@Malum District - Locations/counter at the bar" },
    [273] = { "@Malum District - Locations/kegs at the bar" },
    [274] = { "@Malum District - Locations/small stairs inside bar" },
    [275] = { "@Malum District - Locations/couch inside the bar" },
    [276] = { "@Malum District - Locations/chest near Merchant" },
    [277] = { "@Malum District - Locations/Black Rabbit Brotherhood drop" },
    [280] = { "@Malum District - Locations/hanging puppet" },
    [281] = { "@Malum District - Locations/chest in Black Rabbit Brotherhood hideout" },
    [282] = { "@Malum District - Locations/upstairs in Black Rabbit Brotherhood hideout" },

    -- =========================================================
    -- Rosa Isabelle Street (IDs 284-322)
    -- =========================================================

    [284] = { "@Rosa Isabelle Street - Locations/behind destructable objects near staircase" },
    [285] = { "@Rosa Isabelle Street - Locations/across from Gaspard Theatre" },
    [286] = { "@Rosa Isabelle Street - Locations/downstairs near Old Lady at the Window" },
    [287] = { "@Rosa Isabelle Street - Locations/beside Old Lady at the Window" },
    [288] = { "@Rosa Isabelle Street - Locations/wagon near Mrs.Potts building" },
    [289] = { "@Rosa Isabelle Street - Locations/burning gate and shortcut gate" },
    [290] = { "@Rosa Isabelle Street - Locations/before building with exploding puppets" },
    [291] = { "@Rosa Isabelle Street - Locations/shortcut ladder with exploading puppets" },
    [292] = { "@Rosa Isabelle Street - Locations/bed near baby puppets" },
    [293] = { "@Rosa Isabelle Street - Locations/table in room with baby puppets" },
    [294] = { "@Rosa Isabelle Street - Locations/safe next to shortcut door" },
    [295] = { "@Rosa Isabelle Street - Locations/counter in room with maid puppets" },
    [296] = { "@Rosa Isabelle Street - Locations/wagon near the Bar and Grill" },
    [297] = { "@Rosa Isabelle Street - Locations/behind overheat throwing puppet" },
    [298] = { "@Rosa Isabelle Street - Locations/near White Lady" },
    [299] = { "@Rosa Isabelle Street - Locations/The White Lady's Locket" },
    [300] = { "@Rosa Isabelle Street - Locations/The White Lady's Mask" },
    [301] = { "@Rosa Isabelle Street - Locations/corpse next to a wagon after White Lady" },
    [302] = { "@Rosa Isabelle Street - Locations/hidden path behind boxes" },
    [303] = { "@Rosa Isabelle Street - Locations/corner near Red Butterfly in small courtyard" },
    [304] = { "@Rosa Isabelle Street - Locations/Red Butterfly drop" },
    [305] = { "@Rosa Isabelle Street - Locations/behind Red Butterfly" },
    [306] = { "@Rosa Isabelle Street - Locations/chest behind shortcut gate" },
    [307] = { "@Rosa Isabelle Street - Locations/sewers before drop" },
    [308] = { "@Rosa Isabelle Street - Locations/chest in sewers" },
    [309] = { "@Rosa Isabelle Street - Locations/shortcut by White Lady" },
    [310] = { "@Rosa Isabelle Street - Locations/shortcut to Rosa Isabelle Street Culvert stargazer" },
    [311] = { "@Rosa Isabelle Street - Locations/near exploding puppets" },
    [312] = { "@Rosa Isabelle Street - Locations/by rifleman puppet" },
    [313] = { "@Rosa Isabelle Street - Locations/red boxes" },
    [314] = { "@Rosa Isabelle Street - Locations/across bridge" },
    [315] = { "@Rosa Isabelle Street - Locations/safe with baby puppets" },
    [316] = { "@Rosa Isabelle Street - Locations/bush" },
    [317] = { "@Rosa Isabelle Street - Locations/shortcut to Rosa Isabelle Street Entrance stargazer" },
    [318] = { "@Rosa Isabelle Street - Locations/wagon near Mad Clown Puppet" },
    [319] = { "@Rosa Isabelle Street - Locations/ledge near Mad Clown Puppet" },
    [320] = { "@Rosa Isabelle Street - Locations/left side near Mad Clown Puppet" },
    [321] = { "@Rosa Isabelle Street - Locations/volunteers wanted sign" },
    [322] = { "@Rosa Isabelle Street - Locations/Mad Clown Puppet drop" },

    -- =========================================================
    -- Estella Opera House (IDs 323-342, 345-348, 422-423)
    -- =========================================================
    
    [323] = { "@Estella Opera House - Locations/statue by stargazer" },
    [324] = { "@Estella Opera House - Locations/on a bench" },
    [325] = { "@Estella Opera House - Locations/by spotlight" },
    [326] = { "@Estella Opera House - Locations/front of shortcut door" },
    [327] = { "@Estella Opera House - Locations/right side lower balcony" },
    [328] = { "@Estella Opera House - Locations/right side upper balcony" },
    [329] = { "@Estella Opera House - Locations/chest near Adelina" },
    [330] = { "@Estella Opera House - Locations/on a table in hallway" },
    [331] = { "@Estella Opera House - Locations/chest in dark room" },
    [332] = { "@Estella Opera House - Locations/in safe in small room" },
    [333] = { "@Estella Opera House - Locations/sculpture of head" },
    [334] = { "@Estella Opera House - Locations/beside Trinity door" },
    [335] = { "@Estella Opera House - Locations/safe in small room" },
    [336] = { "@Estella Opera House - Locations/dead-end of hallway" },
    [337] = { "@Estella Opera House - Locations/table in hallway" },
    [338] = { "@Estella Opera House - Locations/on desk" },
    [339] = { "@Estella Opera House - Locations/chest next to bookcase" },
    [340] = { "@Estella Opera House - Locations/wood beam" },
    [341] = { "@Estella Opera House - Locations/Red Butterfly drop" },
    [342] = { "@Estella Opera House - Locations/bench" },
    [345] = { "@Estella Opera House - Locations/before King of Puppets" },
    [346] = { "@Estella Opera House - Locations/Burnt-White King's Ergo" },
    [347] = { "@Estella Opera House - Locations/Puppet Prince's Formal Dress" },
    [348] = { "@Estella Opera House - Locations/Someone's Necklace" },
    [422] = { "@Estella Opera House - Locations/Trinity door loot (1)" },
    [423] = { "@Estella Opera House - Locations/Trinity door loot (2)" },

    -- =========================================================
    -- Lorenzini Arcade (IDs 349-385)
    -- =========================================================

    [349] = { "@Lorenzini Arcade - Locations/puppet corpse by red boxes" },
    [350] = { "@Lorenzini Arcade - Locations/small alley" },
    [351] = { "@Lorenzini Arcade - Locations/lamp post" },
    [352] = { "@Lorenzini Arcade - Locations/small room" },
    [353] = { "@Lorenzini Arcade - Locations/upstairs" },
    [354] = { "@Lorenzini Arcade - Locations/dead-end down some stairs" },
    [355] = { "@Lorenzini Arcade - Locations/next to wagon" },
    [356] = { "@Lorenzini Arcade - Locations/market stand" },
    [357] = { "@Lorenzini Arcade - Locations/chest up ladder" },
    [358] = { "@Lorenzini Arcade - Locations/bottom left in courtyard" },
    [359] = { "@Lorenzini Arcade - Locations/top right in courtyard" },
    [360] = { "@Lorenzini Arcade - Locations/top left in courtyard" },
    [361] = { "@Lorenzini Arcade - Locations/small room on floor" },
    [362] = { "@Lorenzini Arcade - Locations/small room on counter" },
    [363] = { "@Lorenzini Arcade - Locations/dead-end near big door" },
    [364] = { "@Lorenzini Arcade - Locations/on small ledge" },
    [365] = { "@Lorenzini Arcade - Locations/Orange Butterfly Drop" },
    [366] = { "@Lorenzini Arcade - Locations/other side of big hole" },
    [367] = { "@Lorenzini Arcade - Locations/Carcass Elite drop" },
    [368] = { "@Lorenzini Arcade - Locations/in blood water" },
    [369] = { "@Lorenzini Arcade - Locations/in bedroom" },
    [370] = { "@Lorenzini Arcade - Locations/on wooden boxes" },
    [371] = { "@Lorenzini Arcade - Locations/in hallway" },
    [372] = { "@Lorenzini Arcade - Locations/corner of circular room" },
    [373] = { "@Lorenzini Arcade - Locations/bathroom" },
    [374] = { "@Lorenzini Arcade - Locations/fountain" },
    [375] = { "@Lorenzini Arcade - Locations/Red Butterfly drop" },
    [376] = { "@Lorenzini Arcade - Locations/second Red Butterfly drop" },
    [377] = { "@Lorenzini Arcade - Locations/safe near decay bubbles" },
    [378] = { "@Lorenzini Arcade - Locations/dead-end near decay bubbles" },
    [379] = { "@Lorenzini Arcade - Locations/next to table at the bar" },
    [380] = { "@Lorenzini Arcade - Locations/between two tables at the bar" },
    [381] = { "@Lorenzini Arcade - Locations/drop from jester elite puppet" },
    [382] = { "@Lorenzini Arcade - Locations/carcass jail cell" },
    [383] = { "@Lorenzini Arcade - Locations/in front of barrels jester elite smashes" },
    [384] = { "@Lorenzini Arcade - Locations/next to pillar" },
    [385] = { "@Lorenzini Arcade - Locations/next to big shortcut gate" },

    -- =========================================================
    -- Grand Exhibition (IDs 386-421)
    -- =========================================================

    [386] = { "@Grand Exhibition - Locations/on staircase" },
    [387] = { "@Grand Exhibition - Locations/near lamp" },
    [388] = { "@Grand Exhibition - Locations/tree" },
    [389] = { "@Grand Exhibition - Locations/Elite Puppet drop" },
    [390] = { "@Grand Exhibition - Locations/bench" },
    [391] = { "@Grand Exhibition - Locations/before tram" },
    [392] = { "@Grand Exhibition - Locations/red box before big door" },
    [393] = { "@Grand Exhibition - Locations/dead-end behind curtains" },
    [394] = { "@Grand Exhibition - Locations/counter" },
    [395] = { "@Grand Exhibition - Locations/second dead-end behind curtains" },
    [396] = { "@Grand Exhibition - Locations/small stage" },
    [397] = { "@Grand Exhibition - Locations/blue Grand Exhibition sign" },
    [398] = { "@Grand Exhibition - Locations/Purple Butterfly drop" },
    [399] = { "@Grand Exhibition - Locations/Puppet Elite drop" },
    [400] = { "@Grand Exhibition - Locations/chest outside" },
    [401] = { "@Grand Exhibition - Locations/metal beam item" },
    [402] = { "@Grand Exhibition - Locations/metal beam" },
    [403] = { "@Grand Exhibition - Locations/next to shortcut" },
    [404] = { "@Grand Exhibition - Locations/by wooden crates" },
    [405] = { "@Grand Exhibition - Locations/near wooden crates" },
    [406] = { "@Grand Exhibition - Locations/chest by wooden crates" },
    [407] = { "@Grand Exhibition - Locations/jumpscare" },
    [408] = { "@Grand Exhibition - Locations/inside train" },
    [409] = { "@Grand Exhibition - Locations/tank" },
    [410] = { "@Grand Exhibition - Locations/ledge above train" },
    [411] = { "@Grand Exhibition - Locations/chest above train" },
    [412] = { "@Grand Exhibition - Locations/mini Victor Elite drop" },
    [413] = { "@Grand Exhibition - Locations/chest near Victor" },
    [414] = { "@Grand Exhibition - Locations/left platform (1)" },
    [415] = { "@Grand Exhibition - Locations/right platform" },
    [416] = { "@Grand Exhibition - Locations/left platform (2)" },
    [417] = { "@Grand Exhibition - Locations/left platform (3)" },
    [418] = { "@Grand Exhibition - Locations/before Victor" },
    [419] = { "@Grand Exhibition - Locations/received by resting at a stargazer after Victor is killed" },
    [420] = { "@Grand Exhibition - Locations/Champion Victor drop" },
    [421] = { "@Grand Exhibition - Locations/behind Saintless of Mercy Statue" },

    -- =========================================================
    -- Barren Swamp (IDs 424-494, 499-505)
    -- =========================================================

    [424] = { "@Barren Swamp - Locations/next to box inside train station" },
    [425] = { "@Barren Swamp - Locations/table in room with hanging puppets" },
    [426] = { "@Barren Swamp - Locations/on puppet corpse" },
    [427] = { "@Barren Swamp - Locations/on path by cliffs" },
    [428] = { "@Barren Swamp - Locations/chest on path" },
    [429] = { "@Barren Swamp - Locations/small coruption swamp (1)" },
    [430] = { "@Barren Swamp - Locations/small coruption swamp (2)" },
    [431] = { "@Barren Swamp - Locations/by rolling firball" },
    [432] = { "@Barren Swamp - Locations/Electric Mad Clown Pupped drop" },
    [433] = { "@Barren Swamp - Locations/on tree" },
    [434] = { "@Barren Swamp - Locations/fire pit" },
    [435] = { "@Barren Swamp - Locations/corpse by fire pit" },
    [436] = { "@Barren Swamp - Locations/wood beam" },
    [437] = { "@Barren Swamp - Locations/top of tower" },
    [438] = { "@Barren Swamp - Locations/chest in tower" },
    [439] = { "@Barren Swamp - Locations/ledge across bridge" },
    [440] = { "@Barren Swamp - Locations/turn on path" },
    [441] = { "@Barren Swamp - Locations/tree" },
    [442] = { "@Barren Swamp - Locations/dead-end near first ballista" },
    [443] = { "@Barren Swamp - Locations/pile of corpses near first ballista" },
    [444] = { "@Barren Swamp - Locations/path to first ballista" },
    [445] = { "@Barren Swamp - Locations/on ledge at path to first ballista" },
    [446] = { "@Barren Swamp - Locations/bottom of first ballista tower" },
    [447] = { "@Barren Swamp - Locations/chest by first ballista" },
    [448] = { "@Barren Swamp - Locations/swamp water by first ballista" },
    [449] = { "@Barren Swamp - Locations/ledge on path forward" },
    [450] = { "@Barren Swamp - Locations/campfire" },
    [451] = { "@Barren Swamp - Locations/before large swamp" },
    [452] = { "@Barren Swamp - Locations/Red Butterfly drop (1)" },
    [453] = { "@Barren Swamp - Locations/Puppet of the Future drop (1)" },
    [454] = { "@Barren Swamp - Locations/Purple Butterfly drop (1)" },
    [455] = { "@Barren Swamp - Locations/Orange Butterfly drop" },
    [456] = { "@Barren Swamp - Locations/Purple Butterfly drop (2)" },
    [457] = { "@Barren Swamp - Locations/Red Butterfly drop (2)" },
    [458] = { "@Barren Swamp - Locations/Puppet of the Future drop (2)" },
    [459] = { "@Barren Swamp - Locations/big Swamp (1)" },
    [460] = { "@Barren Swamp - Locations/big Swamp (2)" },
    [461] = { "@Barren Swamp - Locations/big Swamp (3)" },
    [462] = { "@Barren Swamp - Locations/big Swamp (4)" },
    [463] = { "@Barren Swamp - Locations/big Swamp (5)" },
    [464] = { "@Barren Swamp - Locations/big Swamp (6)" },
    [465] = { "@Barren Swamp - Locations/big swamp chest" },
    [466] = { "@Barren Swamp - Locations/big swamp (7)" },
    [467] = { "@Barren Swamp - Locations/big swamp (8)" },
    [468] = { "@Barren Swamp - Locations/ledge in shack" },
    [469] = { "@Barren Swamp - Locations/in shack" },
    [470] = { "@Barren Swamp - Locations/Owl Doctor drop" },
    [471] = { "@Barren Swamp - Locations/before a drop down" },
    [472] = { "@Barren Swamp - Locations/floating platform" },
    [473] = { "@Barren Swamp - Locations/dead-end" },
    [474] = { "@Barren Swamp - Locations/by sand bags" },
    [475] = { "@Barren Swamp - Locations/chest on wood platform" },
    [476] = { "@Barren Swamp - Locations/by wood beam" },
    [477] = { "@Barren Swamp - Locations/wood platform" },
    [478] = { "@Barren Swamp - Locations/dead-end near fire ball" },
    [479] = { "@Barren Swamp - Locations/Red Butterfly drop (3)" },
    [480] = { "@Barren Swamp - Locations/ledge near fire ball second level" },
    [481] = { "@Barren Swamp - Locations/Red Butterfly drop (4)" },
    [482] = { "@Barren Swamp - Locations/on fire ball path" },
    [483] = { "@Barren Swamp - Locations/top of fire ball area" },
    [484] = { "@Barren Swamp - Locations/fire ball ledge" },
    [485] = { "@Barren Swamp - Locations/Red Butterfly Drop (5)" },
    [486] = { "@Barren Swamp - Locations/open room" },
    [487] = { "@Barren Swamp - Locations/chest in open room" },
    [488] = { "@Barren Swamp - Locations/outside small shack" },
    [489] = { "@Barren Swamp - Locations/chest in shack" },
    [490] = { "@Barren Swamp - Locations/Leaping Amulet" },
    [491] = { "@Barren Swamp - Locations/Dark Moon Moonstone of the Covenant" },
    [492] = { "@Barren Swamp - Locations/by campfire" },
    [493] = { "@Barren Swamp - Locations/upper entrance to tower" },
    [494] = { "@Barren Swamp - Locations/bottom of tower" },
    [499] = { "@Barren Swamp - Locations/before Green Monster of the Swamp" },
    [500] = { "@Barren Swamp - Locations/Puppet-Devouring Green Hunter's Ergo" },
    [501] = { "@Barren Swamp - Locations/Golden Ergo" },
    [502] = { "@Barren Swamp - Locations/ledge after drop down" },
    [503] = { "@Barren Swamp - Locations/by firepit" },
    [504] = { "@Barren Swamp - Locations/firepit" },
    [505] = { "@Barren Swamp - Locations/dead-end above entrance from Barren Swamp" },
    [1104] = { "@Barren Swamp - Locations/ledge after bear traps" },

    -- =========================================================
    -- Hermit Cave (IDs 578-593)
    -- =========================================================

    [578] = { "@Hermit Cave - Locations/on table" },
    [579] = { "@Hermit Cave - Locations/dead-end" },
    [580] = { "@Hermit Cave - Locations/on shack roof" },
    [581] = { "@Hermit Cave - Locations/in shack" },
    [582] = { "@Hermit Cave - Locations/dead-end near shack" },
    [583] = { "@Hermit Cave - Locations/path around trip wire" },
    [584] = { "@Hermit Cave - Locations/chest in small shack" },
    [585] = { "@Hermit Cave - Locations/outside small shack" },
    [586] = { "@Hermit Cave - Locations/underneath a small dropdown" },
    [587] = { "@Hermit Cave - Locations/last platform on mutiple drops" },
    [588] = { "@Hermit Cave - Locations/bottom of ladder by stargazer" },
    [589] = { "@Hermit Cave - Locations/chest guarded by strong carcass enemy" },
    [590] = { "@Hermit Cave - Locations/across wooden beam" },
    [591] = { "@Hermit Cave - Locations/after jump by ladder" },
    [592] = { "@Hermit Cave - Locations/Black Cat's Hunting Apparel" },
    [593] = { "@Hermit Cave - Locations/Quartz" },

    




}